# Demo for doing releases automatically on GitHub
name: "GitHub release demo"


on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v2
        with:
          token: "${{ secrets.TOKEN }}"

      - name: Generate release information
        run: |
          echo $GITHUB_REF
          git describe $GITHUB_REF
          git tag --list  --format="%(subject)%0a%(body)" $(git describe $GITHUB_REF) > release.md
          cat release.md

      - name: Create GitHub release
        uses: ncipollo/release-action@v1.8.10
        with:
          token: "${{ secrets.TOKEN }}"
          bodyFile: "release.md"

      - name: Bump version
        run: |
          export VERSION=$(git describe --tags --abbrev=0 | cut -c 2-)
          sed -i -E "s/(Version:\\s+)[0-9].+/\1$VERSION/" osbuild.spec

      - name: Commit new version
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: "Post release version bump"
          add: "*.spec"
