# Demo for doing releases automatically on GitHub
name: "GitHub release demo"

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Upstream release
        uses: ochosi/composite-actions@main
        with:
          token: "${{ secrets.TOKEN }}"
          slack_webhook_url: "${{ secrets.SLACK_WEBHOOK_URL }}"
