# Demo for doing releases automatically on GitHub
name: "GitHub release demo"


on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.TOKEN }}"
        name: Checkout current repo

      - run: |
          echo "github ref: $GITHUB_REF"
          pwd
          printf "# New Release\n  * First change\n  * Second change" > release.md
        name: Generate release information

      - uses: ncipollo/release-action@v1.8.10
        with:
          token: "${{ secrets.TOKEN }}"
          bodyFile: "release.md"
        name: Create GitHub release

      - run: |
          export VERSION=$(git describe --tags --abbrev=0 | cut -c 2-)
          sed -i -E "s/(Version:\\s+)[0-9].+/\1$VERSION/" osbuild.spec
        name: Bump version

      - uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: "Post release version bump"
          add: "*.spec"
        name: Commit new version
