# This is a basic workflow to help you get started with Actions

name: "GitHub release demo"


on:
  push:
    tags:
      - "v*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: ncipollo/release-action@v1.8.10
        with:
          token: "${{ secrets.TOKEN }}"
        name: Create GitHub release

      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.TOKEN }}"
      - run: |
          sed -i -E "s/(Version:\\s+)[0-9]+/\110/" osbuild.spec
        name: Bump version

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          token: "${{ secrets.TOKEN }}"
          commit_message: "Post release version bump"
        name: Commit new version
