# Demo for fedora-bot's composite action
name: "fedora-bot demo"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    name: Check for new releases
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/osbuild/fedora-bot:latest

    steps:
      - name: Upstream release
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo ${{github.ref}}
