# This action creates a release every second Tuesday
name: "Create and push release tag"

on:
  workflow_dispatch:
#  schedule:
#    "0 10 * * tue/2"

jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Upstream tag
        uses: ochosi/composite-actions@main
        with:
          token: "${{ secrets.TOKEN }}"