# This action creates a release every second Tuesday
name: "Create and push release tag"

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  tag-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Even or odd week
        run: if [ `expr \`date +\%s\` / 86400 \% 2` -eq 0 ]; then echo "WEEK='odd'" >> $GITHUB_ENV; else echo "WEEK='even'" >> $GITHUB_ENV; fi
        shell: bash

      - name: Week info
        run: echo ${{ env.WEEK }}
        shell: bash

      - name: Upstream tag
        uses: ochosi/composite-actions@tagging
        if: ${{ env.WEEK == 'odd' }}
        with:
          token: "${{ secrets.TOKEN }}"
          component: "osbuild-composer"
          username: "imagebuilder-bot"
          email: "imagebuilder-bots+imagebuilder-bot@redhat.com"